In [1]:
#=
2024-06-22
借鉴  唐睿代码  中 TangRui_2.mlx
=#

In [2]:
#=
下面代码生成 myshow 宏体
=#

macro myshow(exs...)
    blk = Expr(:block)  #此处使用 头部符号是 block的表达式
    for ex in exs
        push!(blk.args, :(println($(sprint(Base.show_unquoted,ex)*" = "))))
        push!(blk.args, :(show(stdout, "text/plain", begin value=$(esc(ex)) end)))
        push!(blk.args, :(println()))
    end
    isempty(exs) || push!(blk.args, :value)
    return blk
end


@myshow (macro with 1 method)

In [3]:
using LinearAlgebra
using Random

In [4]:
#t1=time_ns()

In [5]:
#参数设置  #分号则不输出结果
L = 4 #初始矩阵大小，对应L*L矩阵
theta = 10
alpha = 0.3
b = 1.2
K = 1 
T = 10^2 #迭代次数,测试时建议使用10^3或10^4，参数分析绘图时改成10^5（需要跑约*min）
H = 10 #额外阈值

10

In [6]:
M=zeros(L,L,4)

4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [7]:
#a11=ones(L)  #错误 这是L*1的列向量

In [8]:
#a12=ones(L,L)

In [9]:
#M(:,:,1)=ones(L,L)  #错误 Julia用方括号表示索引

In [10]:
#M[:,:,1]=ones(L,L)

In [11]:
M[:,:,1] .=1

4×4 view(::Array{Float64, 3}, :, :, 1) with eltype Float64:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [12]:
M[:,:,3] .= b

4×4 view(::Array{Float64, 3}, :, :, 3) with eltype Float64:
 1.2  1.2  1.2  1.2
 1.2  1.2  1.2  1.2
 1.2  1.2  1.2  1.2
 1.2  1.2  1.2  1.2

In [13]:
#rng = MersenneTwister(0);

In [14]:
#rand!(rng, zeros(5))

In [15]:
#zeros(5)

In [16]:
#rand(rng, 5)

In [17]:
#rng = MersenneTwister(0);

In [18]:
#rand(5)

In [19]:
Random.seed!(0)
Strmtx = rand(0:1,L,L)

4×4 Matrix{Int64}:
 0  1  0  0
 0  0  0  0
 1  0  1  0
 0  1  1  1

In [20]:
A_mtx = zeros(L,L) #初始化压力矩阵A  
A_peer = zeros(L,L)
A_self = zeros(L,L)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [21]:
Fc = zeros(T+1,1)  #合作比例。有两个参数T+1, 1，则为 T+1 * 1 的列向量

101×1 Matrix{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [22]:
Fc[1] = sum(Strmtx)/L^2

0.375

In [23]:
overstress = zeros(T+1,1)

101×1 Matrix{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [24]:
str1=zeros(L,L,4)
str2=zeros(L,L,4)

4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [60]:
t=1

1

In [26]:
str1[:,:,1]=Strmtx


4×4 Matrix{Int64}:
 0  1  0  0
 0  0  0  0
 1  0  1  0
 0  1  1  1

In [27]:
str1[:,:,2]=Strmtx


4×4 Matrix{Int64}:
 0  1  0  0
 0  0  0  0
 1  0  1  0
 0  1  1  1

In [28]:
str1[:,:,3] = 1 .-Strmtx


4×4 Matrix{Int64}:
 1  0  1  1
 1  1  1  1
 0  1  0  1
 1  0  0  0

In [29]:
str1[:,:,4] = 1 .- Strmtx

4×4 Matrix{Int64}:
 1  0  1  1
 1  1  1  1
 0  1  0  1
 1  0  0  0

In [30]:
neigh1= circshift(Strmtx, 1)

4×4 Matrix{Int64}:
 0  1  1  1
 0  1  0  0
 0  0  0  0
 1  0  1  0

In [31]:
neigh2= circshift(Strmtx, -1)  #下面的邻居
neigh3= circshift(Strmtx, (0, 1))  #右移一列-左边的邻居
neigh4= circshift(Strmtx, (0, -1))  #右边的邻居

4×4 Matrix{Int64}:
 1  0  0  0
 0  0  0  0
 0  1  0  1
 1  1  1  0

In [32]:
Strneighbor = neigh1 + neigh2 + neigh3 + neigh4

4×4 Matrix{Int64}:
 1  1  2  1
 1  1  1  0
 0  3  1  3
 3  2  3  1

In [33]:
str2[:,:,1] = Strneighbor
str2[:,:,2] = 4 .- Strneighbor
str2[:,:,3] = Strneighbor
str2[:,:,4] = 4 .- Strneighbor     #str2[:,:,4] = str2[:,:,2]

4×4 Matrix{Int64}:
 3  3  2  3
 3  3  3  4
 4  1  3  1
 1  2  1  3

In [34]:
payoffmtx0 = sum(str1.*M.*str2,dims=3)

4×4×1 Array{Float64, 3}:
[:, :, 1] =
 1.2  1.0  2.4  1.2
 1.2  1.2  1.2  0.0
 0.0  3.6  1.0  3.6
 3.6  2.0  3.0  1.0

In [35]:
payoffmtx = dropdims(payoffmtx0, dims=3)

4×4 Matrix{Float64}:
 1.2  1.0  2.4  1.2
 1.2  1.2  1.2  0.0
 0.0  3.6  1.0  3.6
 3.6  2.0  3.0  1.0

In [64]:
A_self .+= (Strneighbor .< 2.5)

4×4 Matrix{Float64}:
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  0.0  2.0  0.0
 0.0  2.0  0.0  2.0

In [37]:
pay1= circshift(payoffmtx, 1)  #行的变动-上下的邻居，首先是下移一行，即上面的邻居
pay2= circshift(payoffmtx, -1)  #下面的邻居
pay3= circshift(payoffmtx, (0, 1))  #右移一列-左边的邻居
pay4= circshift(payoffmtx, (0, -1))  #右边的邻居

4×4 Matrix{Float64}:
 1.0  2.4  1.2  1.2
 1.2  1.2  0.0  1.2
 3.6  1.0  3.6  0.0
 2.0  3.0  1.0  3.6

In [38]:
payoff_average = (pay1 + pay2 + pay3 + pay4) ./4

4×4 Matrix{Float64}:
 1.75  1.7   1.6   1.15
 0.6   1.75  1.15  1.8
 3.0   1.05  2.85  0.5
 1.05  2.8   1.6   2.85

In [65]:
A_peer .+= (payoffmtx .< payoff_average)

4×4 Matrix{Float64}:
 2.0  2.0  0.0  0.0
 0.0  2.0  0.0  2.0
 2.0  0.0  2.0  0.0
 0.0  2.0  0.0  2.0

In [40]:
A_mtx = (1-alpha).*A_self .+ alpha.*A_peer

4×4 Matrix{Float64}:
 1.0  1.0  0.7  0.7
 0.7  1.0  0.7  1.0
 1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0

In [41]:
Agap = max.(theta .- A_mtx, zeros(L))

4×4 Matrix{Float64}:
  9.0   9.0   9.3   9.3
  9.3   9.0   9.3   9.0
  9.0  10.0   9.0  10.0
 10.0   9.0  10.0   9.0

In [42]:
P1=exp.(-Agap)

4×4 Matrix{Float64}:
 0.00012341  0.00012341  9.14242e-5  9.14242e-5
 9.14242e-5  0.00012341  9.14242e-5  0.00012341
 0.00012341  4.53999e-5  0.00012341  4.53999e-5
 4.53999e-5  0.00012341  4.53999e-5  0.00012341

In [43]:
payoffsample = zeros(L,L,4)
payoffsample[:,:,1] = pay1
payoffsample[:,:,2] = pay2
payoffsample[:,:,3] = pay3
payoffsample[:,:,4] = pay4

4×4 Matrix{Float64}:
 1.0  2.4  1.2  1.2
 1.2  1.2  0.0  1.2
 3.6  1.0  3.6  0.0
 2.0  3.0  1.0  3.6

In [44]:
Strsample = zeros(L,L,4)   #注意此处本来有off，但是下面4个层都没有off，乃取消
Strsample[:,:,1] = neigh1
Strsample[:,:,2] = neigh2
Strsample[:,:,3] = neigh3
Strsample[:,:,4] = neigh4

4×4 Matrix{Int64}:
 1  0  0  0
 0  0  0  0
 0  1  0  1
 1  1  1  0

In [45]:
randmtx = rand(1:4,L,L)   #每个个体选择那个邻居

4×4 Matrix{Int64}:
 3  1  2  4
 1  2  3  3
 3  3  2  4
 2  1  3  1

In [46]:
payoffsampleselct =zeros(L,L)
Strsampleselct =zeros(L,L)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [47]:
for i =1:L
    for j = 1:L
        payoffsampleselct[i,j] = payoffsample[i,j,randmtx[i,j]]
        Strsampleselct[i,j] = Strsample[i,j,randmtx[i,j]]
    end
end

In [48]:
K_A = Agap * K./theta

4×4 Matrix{Float64}:
 0.9   0.9  0.93  0.93
 0.93  0.9  0.93  0.9
 0.9   1.0  0.9   1.0
 1.0   0.9  1.0   0.9

In [49]:
P2 = 1 ./ (1 .+ exp.((payoffmtx .-payoffsampleselct)./K_A))

4×4 Matrix{Float64}:
 0.5        0.752336  0.215798  0.5
 0.5        0.935031  0.5       0.791391
 0.982014   0.026597  0.902227  0.026597
 0.0831727  0.855422  0.268941  0.947294

In [50]:
P2[isnan.(P2)] .= 0.5

0-element view(::Vector{Float64}, Int64[]) with eltype Float64

In [51]:
#P1

In [52]:
#P1.*P2

In [53]:
P1P2selectmtx = (P1.*P2 .> rand(L,L))

4×4 BitMatrix:
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [54]:
#P1P2selectmtx

In [55]:
Strmtx[P1P2selectmtx.==1] .= Strsampleselct[P1P2selectmtx.==1]

0-element view(::Vector{Int64}, Int64[]) with eltype Int64

In [56]:
#Strmtx

In [57]:
A_peer[P1P2selectmtx.==1] .= 0

0-element view(::Vector{Float64}, Int64[]) with eltype Float64

In [58]:
A_self[P1P2selectmtx.==1] .= 0

0-element view(::Vector{Float64}, Int64[]) with eltype Float64

In [61]:
Fc[t+1] =sum(Strmtx)/L^2

0.375

In [63]:
overstress[t+1]= sum(A_mtx .>= (theta+H)) /L^2

0.0