In [ ]:
#=
2024-06-11
以 阿雷拉诺 为模版 重命名为  投影矩阵演示
=#

In [1]:
#=
下面代码生成 myshow 宏体
=#

macro myshow(exs...)
    blk = Expr(:block)  #此处使用 头部符号是 block的表达式
    for ex in exs
        push!(blk.args, :(println($(sprint(Base.show_unquoted,ex)*" = "))))
        push!(blk.args, :(show(stdout, "text/plain", begin value=$(esc(ex)) end)))
        push!(blk.args, :(println()))
    end
    isempty(exs) || push!(blk.args, :value)
    return blk
end


@myshow (macro with 1 method)

In [18]:
#=
引入包裹
下面代码块生成X=I的投影矩阵
=#
using LinearAlgebra  
n=2  #T=3期

w=ones(n)  #1向量
u=[0  0]  #0向量
I = Diagonal(w)   #单位矩阵
X=vcat(I,u)
X0=X'*X
X1=inv(X0)
P=X*X1*X'
y=fill(1, n+1)
y2=P*y

@myshow(X, X0, X1, P,y ,y2)

X = 
3×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
 0.0  0.0
X0 = 
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
X1 = 
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
P = 
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  0.0
y = 
3-element Vector{Int64}:
 1
 1
 1
y2 = 
3-element Vector{Float64}:
 1.0
 1.0
 0.0


3-element Vector{Float64}:
 1.0
 1.0
 0.0

In [20]:
#=
下面代码块生成X=I，权重=A的斜交投影矩阵-加权投影矩阵
=#
A=reshape(1:9, 3, 3)
J=A*X
XA=X'*A
X0=XA*X
X1=inv(X0)
P=X*X1*XA
y2=P*y
@myshow(J,XA, X0, X1, P,y2)

J = 
3×2 Matrix{Float64}:
 1.0  4.0
 2.0  5.0
 3.0  6.0
XA = 
2×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  5.0  8.0
X0 = 
2×2 Matrix{Float64}:
 1.0  4.0
 2.0  5.0
X1 = 
2×2 Matrix{Float64}:
 -1.66667    1.33333
  0.666667  -0.333333
P = 
3×3 Matrix{Float64}:
 1.0  2.22045e-16  -1.0
 0.0  1.0           2.0
 0.0  0.0           0.0
y2 = 
3-element Vector{Float64}:
 2.220446049250313e-16
 2.9999999999999996
 0.0


3-element Vector{Float64}:
 2.220446049250313e-16
 2.9999999999999996
 0.0

In [21]:
#=
下面代码块生成X=I，权重=A的伪投影矩阵
=#
J=A*X
XA=X'*A
X0=XA*X
X1=inv(X0)
P=X*X1*X'
y2=P*y
@myshow(J,XA, X0, X1, P,y2)

J = 
3×2 Matrix{Float64}:
 1.0  4.0
 2.0  5.0
 3.0  6.0
XA = 
2×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  5.0  8.0
X0 = 
2×2 Matrix{Float64}:
 1.0  4.0
 2.0  5.0
X1 = 
2×2 Matrix{Float64}:
 -1.66667    1.33333
  0.666667  -0.333333
P = 
3×3 Matrix{Float64}:
 -1.66667    1.33333   0.0
  0.666667  -0.333333  0.0
  0.0        0.0       0.0
y2 = 
3-element Vector{Float64}:
 -0.33333333333333326
  0.3333333333333333
  0.0


3-element Vector{Float64}:
 -0.33333333333333326
  0.3333333333333333
  0.0

In [5]:
#=
下面的代码生成A+矩阵 A=H2=(DD')^-0.5 * D =B' * D = R * A+ =A2
=#

A=B'*D
r=[(2/3)^0.5;(1/2)^0.5]
R=Diagonal(r)

I20=hcat(I,u)
A2=[-0.5   -0.5; 0  -1]
A20=hcat(u,A2)
Ap=I20 + A20
A2=R*Ap
@myshow(A, Ap, A2)

A = 
2×3 Matrix{Float64}:
 -0.816497   0.408248  0.408248
  0.0       -0.707107  0.707107
Ap = 
2×3 Matrix{Float64}:
 1.0  -0.5  -0.5
 0.0   1.0  -1.0
A2 = 
2×3 Matrix{Float64}:
 0.816497  -0.408248  -0.408248
 0.0        0.707107  -0.707107


2×3 Matrix{Float64}:
 0.816497  -0.408248  -0.408248
 0.0        0.707107  -0.707107

In [6]:
#=
下面演示后向正交离差
=#
r2=[(1/2)^0.5; (2/3)^0.5]
R2=Diagonal(r2)

#I2=hcat(u,I)
A3=[-1  0; -0.5   -0.5]
A30=hcat(A3, u)
Am=I2 + A30   #Ap, p=plus + , Am, m=minus -
A3=R2*Am
@myshow(A, Am, A3)

A = 
2×3 Matrix{Float64}:
 -0.816497   0.408248  0.408248
  0.0       -0.707107  0.707107
Am = 
2×3 Matrix{Float64}:
 -1.0   1.0  0.0
 -0.5  -0.5  1.0
A3 = 
2×3 Matrix{Float64}:
 -0.707107   0.707107  0.0
 -0.408248  -0.408248  0.816497


2×3 Matrix{Float64}:
 -0.707107   0.707107  0.0
 -0.408248  -0.408248  0.816497

In [9]:
#=
根据交叉对应。V-1=TT', V=LL', T=(L-1)', T'=L-1
=#
T1=inv(L)
A4=T1*D
@myshow(T1, A3, A4)

T1 = 
2×2 adjoint(::Matrix{Float64}) with eltype Float64:
 0.707107  0.0
 0.408248  0.816497
A3 = 
2×3 Matrix{Float64}:
 -0.707107   0.707107  0.0
 -0.408248  -0.408248  0.816497
A4 = 
2×3 Matrix{Float64}:
 -0.707107   0.707107  0.0
 -0.408248  -0.408248  0.816497


2×3 Matrix{Float64}:
 -0.707107   0.707107  0.0
 -0.408248  -0.408248  0.816497