2024-05-15
演示 阿雷拉诺 第二章 的 几个公式。主要涉及 乔列斯基分解 以及 前向后向 离差
下面代码块生成D矩阵=K2+I2 

In [1]:
using LinearAlgebra
n=2
v = fill(-1, n)
K = Diagonal(v)
w=ones(n)
I = Diagonal(w)
u=zeros(n)
K2=hcat(K,u)
I2=hcat(u,I)
D=K2+I2  
V=D*D'

2×2 Matrix{Float64}:
  2.0  -1.0
 -1.0   2.0

下面的代码块生成V和V-1的乔列斯基分解

In [2]:
cholesky(V)
V1=inv(V)
cholesky(V1)

Cholesky{Float64, Matrix{Float64}}
U factor:
2×2 UpperTriangular{Float64, Matrix{Float64}}:
 0.816497  0.408248
  ⋅        0.707107

检验乔列斯基分解
V1表示逆矩阵, L1表示L的转置  在 不至于引起混淆的情况下，用1表示转置或者逆矩阵
V=LL', V-1=BB'

In [3]:
L1 = [2^0.5  -2^0.5/2; 0  3/6^0.5]
B1= [2/6^0.5  1/6^0.5; 0  1/2^0.5]
L=L1'
B=B1'
V=L*L'
V1=B*B'
V*V1

2×2 Matrix{Float64}:
  1.0          0.0
 -1.11022e-16  1.0

下面的代码生成A+矩阵 A=H2=(DD')^-0.5 * D = R * A+ =A2

In [6]:
A=B'*D
println(A)
r=[2/6^0.5;1/2^0.5]
R=Diagonal(r)

I20=hcat(I,u)
A2=[-0.5   -0.5; 0  -1]
A20=hcat(u,A2)
Ap=I20 + A20
A2=R*Ap


[-0.8164965809277259 0.40824829046386296 0.40824829046386296; 0.0 -0.7071067811865475 0.7071067811865475]


2×3 Matrix{Float64}:
 0.816497  -0.408248  -0.408248
 0.0        0.707107  -0.707107