In [1]:
using LinearAlgebra
using Random
using BenchmarkTools
using Statistics
using StaticArrays

In [2]:
x = (1, -1, (0,1), (0,-1))

(1, -1, (0, 1), (0, -1))

In [5]:
x[1]

1

In [3]:
L = 4

4

In [4]:
Strmtx = rand(0:1,L,L)

4×4 Matrix{Int64}:
 1  0  0  0
 0  1  1  1
 1  0  1  1
 0  0  1  1

In [6]:
Strneighbor = circshift(Strmtx, x[1]) + circshift(Strmtx, x[2]) + circshift(Strmtx, x[3]) + circshift(Strmtx, x[4])

4×4 Matrix{Int64}:
 0  2  2  3
 4  1  3  2
 1  3  3  4
 3  1  2  2

In [11]:
b=1.2
s=1
sn=3

3

In [10]:
M=@SMatrix [1 0; b  0]

2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 1.0  0.0
 1.2  0.0

In [12]:
pay  = [s 1-s] * M * [sn; 4-sn]

1-element Vector{Float64}:
 3.0

In [14]:
pay2  = [s 1-s] * M * [sn, 4-sn]

1-element Vector{Float64}:
 3.0

In [16]:
pay3  = [s 1-s] * M * (sn, 4-sn)

MethodError: MethodError: no method matching *(::Matrix{Float64}, ::Tuple{Int64, Int64})

Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:587
  *(::Union{Adjoint{<:Any, <:StridedMatrix{T}}, Transpose{<:Any, <:StridedMatrix{T}}, StridedArray{T, 2}} where T, !Matched::Union{Adjoint{var"#s390", var"#s389"}, Transpose{var"#s390", var"#s389"}} where {var"#s390", var"#s389"<:SparseArrays.AbstractSparseMatrixCSC})
   @ SparseArrays C:\Users\xingfu_2\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\SparseArrays\src\linalg.jl:167
  *(::Union{Adjoint{<:Any, <:StridedMatrix{var"#s994"}}, Transpose{<:Any, <:StridedMatrix{var"#s994"}}, StridedMatrix{var"#s994"}} where var"#s994"<:Union{Float32, Float64}, !Matched::Union{Adjoint{<:Any, <:StridedMatrix{var"#s128"}}, Transpose{<:Any, <:StridedMatrix{var"#s128"}}} where var"#s128"<:Union{ComplexF64, ComplexF32})
   @ LinearAlgebra C:\Users\xingfu_2\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\LinearAlgebra\src\matmul.jl:147
  ...


In [36]:
strmtx = rand(0:1,L,L)

4×4 Matrix{Int64}:
 0  1  0  1
 1  1  0  1
 0  1  0  0
 0  1  1  1

In [18]:
Strneighbor = circshift(Strmtx, 1) + circshift(Strmtx, -1) + circshift(Strmtx, (0, 1)) + circshift(Strmtx, (0, -1))

4×4 Matrix{Int64}:
 3  2  2  3
 2  3  1  2
 2  1  1  2
 3  2  2  1

In [19]:
payoffmtx = zeros(L,L)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [32]:
for i = 1:L
    for j = 1:L
        payoffmtx[i,j] = (@views [Strmtx[i,j] 1-Strmtx[i,j]] * M * [Strneighbor[i,j]; 4-Strneighbor[i,j]])[1]
    end
end

In [33]:
randmtx = @SMatrix rand(1:4,L,L)

4×4 SMatrix{4, 4, Int64, 16} with indices SOneTo(4)×SOneTo(4):
 2  4  3  4
 2  2  3  2
 1  3  2  3
 3  1  2  3

In [55]:
randten= zeros(L,L,4)  #每个个体选择一个邻居

4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [56]:
randmtx = rand(1:4,L,L)

4×4 Matrix{Int64}:
 3  3  1  3
 2  4  3  1
 1  4  2  3
 2  4  3  3

In [57]:
for i =1:4
    randten[:,:,i] = (i.==randmtx)
end

In [58]:
randten

4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0

[:, :, 3] =
 1.0  1.0  0.0  1.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
 0.0  0.0  1.0  1.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0

In [34]:
strselct = zeros(L,L)
#payselct =zeros(L,L)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [ ]:
@views circshift(strmtx, x[randmtx[i,j]])

In [40]:
x = ((1,0), (-1,0), (0,1), (0,-1))

((1, 0), (-1, 0), (0, 1), (0, -1))

In [51]:
for i =1:L
    for j = 1:L
        nei=rand(1:4,1)[1]
        i0=mod(i+x[nei][1]-1, L) +1
        j0=mod(j+x[nei][2]-1, L) +1
        strselct[i,j] = @views strmtx[i0, j0]
        #payselct[i,j] = @views paymtx[i0, j0]
    end
end

In [44]:
a=rand(1:4,1)[1]

2

In [49]:
for i =1:L
    for j = 1:L
        a=rand(1:4,1)[1]
        strselct[i,j] = @views strmtx[mod(i+x[a][1]-1, L)+1,mod(j+x[a][2]-1, L)+1]
        #payselct[i,j] = @views circshift(paymtx, x[randmtx[i,j]])
    end
end

In [21]:
for i = 1:L
    for j = 1:L
        payoffmtx[i,j] = [Strmtx[i,j] 1-Strmtx[i,j]] * M * [Strneighbor[i,j]; 4-Strneighbor[i,j]]
    end
end

MethodError: MethodError: Cannot `convert` an object of type Vector{Float64} to an object of type Float64

Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, !Matched::T) where T
   @ Base Base.jl:84
  convert(::Type{T}, !Matched::Number) where T<:Number
   @ Base number.jl:7
  ...


In [31]:
payoffmtx[1,1] = (@views [Strmtx[1,1] 1-Strmtx[1,1]] * M * [Strneighbor[1,1]; 4-Strneighbor[1,1]])[1]

3.0

In [28]:
[Strneighbor[1,1]; 4-Strneighbor[1,1]]

2-element Vector{Int64}:
 3
 1

In [29]:
 [Strmtx[1,1] 1-Strmtx[1,1]] * M * [Strneighbor[1,1]; 4-Strneighbor[1,1]]

1-element Vector{Float64}:
 3.0

In [7]:
circshift(Strmtx, 1) + circshift(Strmtx, -1) + circshift(Strmtx, (0, 1)) + circshift(Strmtx, (0, -1))

4×4 Matrix{Int64}:
 0  2  2  3
 4  1  3  2
 1  3  3  4
 3  1  2  2

In [2]:
a=[[1,2], 3]

2-element Vector{Any}:
  [1, 2]
 3

In [5]:
a[1]

2-element Vector{Int64}:
 1
 2

In [3]:
b=[[1;2];3]

3-element Vector{Int64}:
 1
 2
 3

In [4]:
c=[[1 2], 3]

2-element Vector{Any}:
  [1 2]
 3

In [6]:
c[1]

1×2 Matrix{Int64}:
 1  2

In [7]:
d=[[1 2]; 3]

DimensionMismatch: DimensionMismatch: mismatch in dimension 2 (expected 2 got 1)

In [8]:
e=[11, 22, 33, 44]

4-element Vector{Int64}:
 11
 22
 33
 44

In [9]:
e2=[11; 22; 33; 44]

4-element Vector{Int64}:
 11
 22
 33
 44

In [10]:
e3=[11 22 33 44]

1×4 Matrix{Int64}:
 11  22  33  44

In [1]:
a = rand(1:4,1)

1-element Vector{Int64}:
 4

In [4]:
b=3
a2=a[1]
c=a2+b

7

In [2]:
#=
下面代码生成 myshow 宏体
=#

macro myshow(exs...)
    blk = Expr(:block)  #此处使用 头部符号是 block的表达式
    for ex in exs
        push!(blk.args, :(println($(sprint(Base.show_unquoted,ex)*" = "))))
        push!(blk.args, :(show(stdout, "text/plain", begin value=$(esc(ex)) end)))
        push!(blk.args, :(println()))
    end
    isempty(exs) || push!(blk.args, :value)
    return blk
end


@myshow (macro with 1 method)

In [2]:
X=reshape(1:24, 4, 3, 2)

4×3×2 reshape(::UnitRange{Int64}, 4, 3, 2) with eltype Int64:
[:, :, 1] =
 1  5   9
 2  6  10
 3  7  11
 4  8  12

[:, :, 2] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

In [1]:
random_number = rand()
random_integer = rand(1:10)
Random_Array = rand(5)
Random_2DArray = rand(4,2)

4×2 Matrix{Float64}:
 0.861164  0.654148
 0.834046  0.870851
 0.773539  0.499019
 0.202354  0.643797

In [3]:
@myshow(random_number, random_integer, Random_Array, Random_2DArray)

random_number = 
0.0023039469119398026
random_integer = 
6
Random_Array = 
5-element Vector{Float64}:
 0.25615543412120645
 0.36746429131455205
 0.4211593365228061
 0.03772193151694203
 0.06363550442627453
Random_2DArray = 
4×2 Matrix{Float64}:
 0.861164  0.654148
 0.834046  0.870851
 0.773539  0.499019
 0.202354  0.643797


4×2 Matrix{Float64}:
 0.861164  0.654148
 0.834046  0.870851
 0.773539  0.499019
 0.202354  0.643797

In [1]:
a51=1
a52=3

3

In [2]:
a52+= a51>0

4

In [17]:
P2=1

1

In [40]:
A = reshape(1:9, 3, 3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [43]:
A[A.> 6] .= 99

CanonicalIndexError: CanonicalIndexError: setindex! not defined for UnitRange{Int64}

In [45]:
A2=ifelse.(A.> 6, 99, A)

3×3 Matrix{Int64}:
 1  4  99
 2  5  99
 3  6  99

In [41]:
A2=[1 4 7; 2 5 8; 3 6 9]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [42]:
A == A2

true

In [46]:
A=[1 4 7; 2 NaN 8; 3 6 9]

3×3 Matrix{Float64}:
 1.0    4.0  7.0
 2.0  NaN    8.0
 3.0    6.0  9.0

In [47]:
A[isnan.(A)] .= 0.5

1-element view(::Vector{Float64}, [5]) with eltype Float64:
 0.5

In [48]:
A

3×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  0.5  8.0
 3.0  6.0  9.0

In [26]:
A.> 13

4×4 BitMatrix:
 0  0  0  0
 0  0  0  1
 0  0  0  1
 0  0  0  1

In [37]:
A[A.> 6] .= 99

3-element view(::Vector{Int64}, [3, 6, 9]) with eltype Int64:
 99
 99
 99

In [38]:
A

3×3 Matrix{Int64}:
  1   2   3
  4   5   6
 99  99  99

In [21]:
B=[0.542545+0.0im        0.925355-0.487208im    1.65225+0.806615im;
 -0.927869+0.847093im  -0.309946+1.53378im    0.444565+0.0im;
 -0.048035+0.260424im   0.937434+0.0im       -0.153685-1.71329im]

3×3 Matrix{ComplexF64}:
  0.542545+0.0im        0.925355-0.487208im    1.65225+0.806615im
 -0.927869+0.847093im  -0.309946+1.53378im    0.444565+0.0im
 -0.048035+0.260424im   0.937434+0.0im       -0.153685-1.71329im

In [24]:
imag.(B) .== 0

3×3 BitMatrix:
 1  0  0
 0  0  1
 0  1  0

In [22]:
B[imag.(B) .== 0] .= 0

3-element view(::Vector{ComplexF64}, [1, 6, 8]) with eltype ComplexF64:
 0.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im

In [23]:
B

3×3 Matrix{ComplexF64}:
       0.0+0.0im        0.925355-0.487208im    1.65225+0.806615im
 -0.927869+0.847093im  -0.309946+1.53378im         0.0+0.0im
 -0.048035+0.260424im        0.0+0.0im       -0.153685-1.71329im

In [28]:
D= randn(5,5)

5×5 Matrix{Float64}:
  1.20767      1.21683   -0.306274   0.149945  -0.591947
  2.28043     -1.39367   -0.486784  -1.80541    1.12534
 -1.47578      1.04202   -1.96426    0.807464   0.154497
  0.00412986  -0.631175  -2.91781   -0.173033  -0.708887
 -0.335264     1.17218   -0.752343   0.168561  -2.28597

In [29]:
D[D.> 0] .= 0.99

11-element view(::Vector{Float64}, [1, 2, 4, 6, 8, 10, 16, 18, 20, 22, 23]) with eltype Float64:
 0.99
 0.99
 0.99
 0.99
 0.99
 0.99
 0.99
 0.99
 0.99
 0.99
 0.99

In [30]:
D

5×5 Matrix{Float64}:
  0.99       0.99      -0.306274   0.99      -0.591947
  0.99      -1.39367   -0.486784  -1.80541    0.99
 -1.47578    0.99      -1.96426    0.99       0.99
  0.99      -0.631175  -2.91781   -0.173033  -0.708887
 -0.335264   0.99      -0.752343   0.99      -2.28597

In [11]:
a87=A51 .> 13

4×4 BitMatrix:
 0  0  0  0
 0  0  0  1
 0  0  0  1
 0  0  0  1

In [13]:
B37 = randn(5,5)

5×5 Matrix{Float64}:
  1.44533   0.390232   -0.797102   -0.169879    0.293348
  2.39597  -1.24218    -0.153451    1.20387    -0.829405
 -1.87073   0.244312    1.84927    -2.10922    -0.401217
  2.26878  -0.0627532  -0.794684    0.0172295  -0.499483
  0.28129   0.288739   -0.0133195  -1.09541    -0.901257

In [15]:
s37 = B37 .> 0

5×5 BitMatrix:
 1  1  0  0  1
 1  0  0  1  0
 0  1  1  0  0
 1  0  0  1  0
 1  1  0  0  0

In [16]:
B37[s37]

11-element Vector{Float64}:
 1.4453338420069672
 2.3959712306325494
 2.268784085170729
 0.28129030329030213
 0.39023171874539275
 0.24431179732729774
 0.2887385221025726
 1.8492732729644576
 1.2038672067000211
 0.01722954407424916
 0.2933481092984233

In [12]:
A51[a87].=99

CanonicalIndexError: CanonicalIndexError: setindex! not defined for UnitRange{Int64}

In [5]:
sum(A51, dims=1)

1×3 Matrix{Int64}:
 6  15  24

In [7]:
a7 = rand(4,3,2)
b7 = sum(a7, dims=1)

1×3×2 Array{Float64, 3}:
[:, :, 1] =
 2.01808  2.18171  1.85897

[:, :, 2] =
 2.1655  1.58273  2.5997

In [9]:
c7 = dropdims(b7, dims=1)

3×2 Matrix{Float64}:
 2.01808  2.1655
 2.18171  1.58273
 1.85897  2.5997

In [3]:
cvec_1 = rand(50000,3)

50000×3 Matrix{Float64}:
 0.554491   0.377351  0.238357
 0.0537227  0.854951  0.440421
 0.014085   0.241895  0.41575
 0.554228   0.334421  0.0697084
 0.808242   0.819667  0.881465
 0.471148   0.986754  0.484243
 0.618295   0.993319  0.932889
 0.0996123  0.15871   0.197258
 0.497963   0.355144  0.383308
 0.949001   0.6237    0.279528
 ⋮                    
 0.687219   0.966468  0.0644698
 0.322404   0.843135  0.309221
 0.658955   0.141641  0.17706
 0.0615017  0.928281  0.893731
 0.443489   0.804617  0.948264
 0.649635   0.355969  0.378837
 0.488995   0.874005  0.0907017
 0.682394   0.188903  0.958518
 0.803152   0.469744  0.995158

In [2]:
function normalize_by_row(arr)
    arr ./ sqrt.(sum(arr.^2, dims=2))
 end

normalize_by_row (generic function with 1 method)

In [4]:
@btime nrm = normalize_by_row($cvec_1)

  863.000 μs (10 allocations: 2.67 MiB)


50000×3 Matrix{Float64}:
 0.778992   0.530131  0.334862
 0.0557739  0.887594  0.457237
 0.0292703  0.502684  0.863975
 0.851284   0.513665  0.107071
 0.557463   0.565343  0.607966
 0.393973   0.82512   0.404922
 0.413184   0.6638    0.623417
 0.366127   0.583341  0.725027
 0.689875   0.492014  0.531032
 0.811456   0.533303  0.239014
 ⋮                    
 0.578643   0.813773  0.054284
 0.33789    0.883633  0.324073
 0.945586   0.203252  0.254078
 0.0476737  0.719567  0.692785
 0.33589    0.609402  0.718197
 0.780793   0.427836  0.455322
 0.486273   0.869139  0.0901967
 0.572632   0.158518  0.804341
 0.589525   0.344799  0.730461

In [10]:
function normalize_by_row_v7(arr)
    u = similar(arr)
    @inbounds for i in axes(arr, 1)
        anorm2 = zero(eltype(arr))
        for j in axes(arr, 2)
            anorm2 += arr[i, j]^2
        end
        anorm = sqrt(anorm2)
        for j in axes(arr, 2)
            u[i, j] = arr[i, j] / anorm
        end
    end
end

normalize_by_row_v7 (generic function with 1 method)

In [12]:
@btime nrm = normalize_by_row_v7($cvec_1)

  567.700 μs (2 allocations: 1.14 MiB)


In [5]:
mynormalize!(arr::AbstractArray{<:AbstractVector}) = (arr ./= norm.(arr))

mynormalize! (generic function with 1 method)

In [4]:
X = rand(SVector{3, Float64}, 50_000)

50000-element Vector{SVector{3, Float64}}:
 [0.4486836083589262, 0.167503544426166, 0.22121989423052468]
 [0.26298972590796343, 0.39750206226566465, 0.5663683275207405]
 [0.0895981605365983, 0.6402584629158077, 0.34935828117491274]
 [0.5203389593023408, 0.8355474452382763, 0.735385056247932]
 [0.2107502433465126, 0.8574698277234656, 0.4053239291390791]
 [0.024964278619923452, 0.9953143381855766, 0.16802354750788728]
 [0.8839033315700137, 0.2552211544590056, 0.5869621229764529]
 [0.39316038395609587, 0.7153870771311084, 0.7602284050474307]
 [0.8007261294547794, 0.49063185736946335, 0.6970655996692291]
 [0.9740576970548961, 0.6332754925501162, 0.8675038362852101]
 ⋮
 [0.552918202689393, 0.7838005851294138, 0.16024319637888085]
 [0.15314572223290224, 0.3028452916926432, 0.9220114077792563]
 [0.0824247706068606, 0.9825885980408441, 0.006302300681656936]
 [0.7411879218013111, 0.7659550385291587, 0.3077819490505971]
 [0.005182714477631412, 0.7580174049835143, 0.5194613568173512]
 [0.74507043

In [5]:
X[1]

3-element SVector{3, Float64} with indices SOneTo(3):
 0.4486836083589262
 0.167503544426166
 0.22121989423052468

In [6]:
X[1][1]=1


ErrorException: setindex!(::SVector{3, Float64}, value, ::Int) is not defined.
 Hint: Use `MArray` or `SizedArray` to create a mutable static array

In [7]:
v1 = SVector(1, 2, 3)

3-element SVector{3, Int64} with indices SOneTo(3):
 1
 2
 3

In [8]:
v1[1]=5

ErrorException: setindex!(::SVector{3, Int64}, value, ::Int) is not defined.
 Hint: Use `MArray` or `SizedArray` to create a mutable static array

In [9]:
v3 = @SVector [1, 2, 3]

3-element SVector{3, Int64} with indices SOneTo(3):
 1
 2
 3

In [10]:
m3 = SMatrix{3,3}(1I)

3×3 SMatrix{3, 3, Int64, 9} with indices SOneTo(3)×SOneTo(3):
 1  0  0
 0  1  0
 0  0  1

In [11]:
v2 = SVector{3,Float64}(1, 2, 3)

3-element SVector{3, Float64} with indices SOneTo(3):
 1.0
 2.0
 3.0

In [12]:
v7 = SVector{3}([1, 2, 3])

3-element SVector{3, Int64} with indices SOneTo(3):
 1
 2
 3

In [13]:
v7 = v1 + v2

3-element SVector{3, Float64} with indices SOneTo(3):
 2.0
 4.0
 6.0

In [16]:
L=4

4

In [17]:
M=@SArray zeros(L,L,4)

4×4×4 SArray{Tuple{4, 4, 4}, Float64, 3, 64} with indices SOneTo(4)×SOneTo(4)×SOneTo(4):
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [18]:
M[:,:,1] .=1

ErrorException: setindex!(::SMatrix{4, 4, Float64, 16}, value, ::Int) is not defined.
 Hint: Use `MArray` or `SizedArray` to create a mutable static array

In [19]:
M=2 .+M

4×4×4 SArray{Tuple{4, 4, 4}, Float64, 3, 64} with indices SOneTo(4)×SOneTo(4)×SOneTo(4):
[:, :, 1] =
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0

[:, :, 2] =
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0

[:, :, 3] =
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0

[:, :, 4] =
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0

In [14]:
v7[1]=8

ErrorException: setindex!(::SVector{3, Float64}, value, ::Int) is not defined.
 Hint: Use `MArray` or `SizedArray` to create a mutable static array

In [15]:
v7=3 .*v1

3-element SVector{3, Int64} with indices SOneTo(3):
 3
 6
 9

In [20]:
b=1.2

1.2

In [22]:
s=[b 5-b]

1×2 Matrix{Float64}:
 1.2  3.8

In [23]:
s2=[b; 5-b]

2-element Vector{Float64}:
 1.2
 3.8

In [21]:
M=@SMatrix [1 0; b  0]

2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 1.0  0.0
 1.2  0.0

In [7]:
@btime mynormalize!($X)

  185.200 μs (0 allocations: 0 bytes)


50000-element Vector{SVector{3, Float64}}:
 [0.5527026508466687, 0.6876157808147436, 0.4708548796833223]
 [0.7762851064251457, 0.436660097026323, 0.4546530470671702]
 [0.7255591415962568, 0.6315361051794818, 0.27336071389435906]
 [0.7374207745376817, 0.004445406764182124, 0.6754190104216393]
 [0.5308942372016445, 0.6820481929953437, 0.5029528520029192]
 [0.5148389458340283, 0.6719776084012169, 0.5323410125660875]
 [0.8600542523234086, 0.4810591668641102, 0.16996694101039397]
 [0.17312247482949983, 0.722575691738932, 0.6692630113915703]
 [0.20391630904791855, 0.8146348156502352, 0.5429440634492482]
 [0.5541983141842237, 0.6165691221294093, 0.5592018832156542]
 ⋮
 [0.7488649464931151, 0.41446627766844274, 0.5171257067575826]
 [0.18550649429260152, 0.5600576275308514, 0.8074173607371736]
 [0.6782753138486801, 0.4019290354587662, 0.615138723442656]
 [0.6790281315307519, 0.08110914767410357, 0.729617778534375]
 [0.193047313866182, 0.3022242501903569, 0.9334844600773644]
 [0.5869896889347288

In [52]:
function myloop(;L = 100,theta = 10, alpha = 0.3, b = 1.2, K = 1, T = 10^3, H = 10)
    #Random.seed!(0)
    
    M=zeros(L,L,4)
    M[:,:,1] .=1
    M[:,:,3] .= b

    Strmtx = rand(0:1,L,L)

    A_mtx = zeros(L,L) #初始化压力矩阵A  
    A_peer = zeros(L,L)
    A_self = zeros(L,L)

    Fc = zeros(T+1,1)  #合作比例。有两个参数T+1, 1，则为 T+1 * 1 的列向量
    Fc[1] = sum(Strmtx)/L^2
    overstress = zeros(T+1,1)

    str1=zeros(L,L,4)  #自己
    str2=zeros(L,L,4)   #邻居

    Strsample = zeros(L,L,4)   #注意此处本来有off，但是下面4个层都没有off，乃取消
    payoffsample = zeros(L,L,4)

    payoffsampleselct =zeros(L,L)
    Strsampleselct =zeros(L,L)

    for t = 1:T
        #4个邻居的策略
        Strsample[:,:,1]= circshift(Strmtx, 1)
        Strsample[:,:,2]= circshift(Strmtx, -1)  #下面的邻居
        Strsample[:,:,3]= circshift(Strmtx, (0, 1))  #右移一列-左边的邻居
        Strsample[:,:,4]= circshift(Strmtx, (0, -1))  #右边的邻居
        Strneighbor = dropdims(sum(Strsample,dims=3), dims=3)

        str1[:,:,1]=Strmtx
        str1[:,:,2]=Strmtx
        str1[:,:,3] = 1 .- Strmtx
        str1[:,:,4] = 1 .- Strmtx

        str2[:,:,1] = Strneighbor
        str2[:,:,2] = 4 .- Strneighbor
        str2[:,:,3] = Strneighbor
        str2[:,:,4] = 4 .- Strneighbor    

        payoffmtx = dropdims(sum(str1.*M.*str2,dims=3), dims=3)
        
        A_self +=  (Strneighbor .< 2.5)

        payoffsample[:,:,1]= circshift(payoffmtx, 1)  #行的变动-上下的邻居，首先是下移一行，即上面的邻居
        payoffsample[:,:,2]= circshift(payoffmtx, -1)  #下面的邻居
        payoffsample[:,:,3]= circshift(payoffmtx, (0, 1))  #右移一列-左边的邻居
        payoffsample[:,:,4]= circshift(payoffmtx, (0, -1))  #右边的邻居
       
        payoff_average = dropdims(sum(payoffsample,dims=3), dims=3)./4

        A_peer += (payoffmtx .< payoff_average)

        A_mtx = (1-alpha).*A_self + alpha.*A_peer
        Agap = max.(theta .- A_mtx, 0)
        P1=exp.(-Agap)
 
        randmtx = rand(1:4,L,L)   #每个个体选择一个邻居

        for i =1:L
            for j = 1:L
                payoffsampleselct[i,j] = payoffsample[i,j,randmtx[i,j]]
                Strsampleselct[i,j] = Strsample[i,j,randmtx[i,j]]
            end
        end
        K_A = Agap * K./theta
        P2 = 1 ./ (1 .+ exp.((payoffmtx .-payoffsampleselct)./K_A))
        P2[isnan.(P2)] .= 0.5

        P1P2selectmtx = (P1.*P2 .> rand(L,L))

        Strmtx[P1P2selectmtx.==1] .= Strsampleselct[P1P2selectmtx.==1]

        A_peer[P1P2selectmtx.==1] .= 0
        A_self[P1P2selectmtx.==1] .= 0
        Fc[t+1] =sum(Strmtx)/L^2
        overstress[t+1]= sum(A_mtx .>= (theta+H)) /L^2
    end
    return Fc, overstress
end

myloop (generic function with 1 method)

In [53]:
@btime myloop();

  1.380 s (124028 allocations: 2.53 GiB)


In [4]:
function myloop2(;L = 100,theta = 10, alpha = 0.3, b = 1.2, K = 1, T = 10^3, H = 10)
    #Random.seed!(0)
    
    M=@SArray zeros(L,L,4)
    M[:,:,1] .=1
    M[:,:,3] .= b

    Strmtx = @SMatrix rand(0:1,L,L)

    A_mtx = @SMatrix zeros(L,L) #初始化压力矩阵A  
    A_peer = @SMatrix zeros(L,L)
    A_self = @SMatrix zeros(L,L)

    Fc = @SVector zeros(T+1)  #合作比例。有两个参数T+1, 1，则为 T+1 * 1 的列向量
    Fc[1] = sum(Strmtx)/L^2
    overstress = @SVector zeros(T+1)

    str1=@SArray zeros(L,L,4)  #自己
    str2=@SArray zeros(L,L,4)   #邻居

    Strsample = @SArray zeros(L,L,4)   #注意此处本来有off，但是下面4个层都没有off，乃取消
    payoffsample = @SArray zeros(L,L,4)

    payoffsampleselct =@SMatrix zeros(L,L)
    Strsampleselct =@SMatrix zeros(L,L)

    for t = 1:T
        #4个邻居的策略
        Strsample[:,:,1]= circshift(Strmtx, 1)
        Strsample[:,:,2]= circshift(Strmtx, -1)  #下面的邻居
        Strsample[:,:,3]= circshift(Strmtx, (0, 1))  #右移一列-左边的邻居
        Strsample[:,:,4]= circshift(Strmtx, (0, -1))  #右边的邻居
        Strneighbor = dropdims(sum(Strsample,dims=3), dims=3)

        str1[:,:,1]=Strmtx
        str1[:,:,2]=Strmtx
        str1[:,:,3] = 1 .- Strmtx
        str1[:,:,4] = 1 .- Strmtx

        str2[:,:,1] = Strneighbor
        str2[:,:,2] = 4 .- Strneighbor
        str2[:,:,3] = Strneighbor
        str2[:,:,4] = 4 .- Strneighbor    

        payoffmtx = dropdims(sum(str1.*M.*str2,dims=3), dims=3)
        
        A_self +=  (Strneighbor .< 2.5)

        payoffsample[:,:,1]= circshift(payoffmtx, 1)  #行的变动-上下的邻居，首先是下移一行，即上面的邻居
        payoffsample[:,:,2]= circshift(payoffmtx, -1)  #下面的邻居
        payoffsample[:,:,3]= circshift(payoffmtx, (0, 1))  #右移一列-左边的邻居
        payoffsample[:,:,4]= circshift(payoffmtx, (0, -1))  #右边的邻居
       
        payoff_average = dropdims(sum(payoffsample,dims=3), dims=3)./4

        A_peer += (payoffmtx .< payoff_average)

        A_mtx = (1-alpha).*A_self + alpha.*A_peer
        Agap = max.(theta .- A_mtx, 0)
        P1=exp.(-Agap)
 
        randmtx = rand(1:4,L,L)   #每个个体选择一个邻居

        for i =1:L
            for j = 1:L
                payoffsampleselct[i,j] = payoffsample[i,j,randmtx[i,j]]
                Strsampleselct[i,j] = Strsample[i,j,randmtx[i,j]]
            end
        end
        K_A = Agap * K./theta
        P2 = 1 ./ (1 .+ exp.((payoffmtx .-payoffsampleselct)./K_A))
        P2[isnan.(P2)] .= 0.5

        P1P2selectmtx = (P1.*P2 .> rand(L,L))

        Strmtx[P1P2selectmtx.==1] .= Strsampleselct[P1P2selectmtx.==1]

        A_peer[P1P2selectmtx.==1] .= 0
        A_self[P1P2selectmtx.==1] .= 0
        Fc[t+1] =sum(Strmtx)/L^2
        overstress[t+1]= sum(A_mtx .>= (theta+H)) /L^2
    end
    return Fc, overstress
end

myloop2 (generic function with 1 method)

In [ ]:
@btime myloop2();