In [2]:
using CSV

In [1]:
using LinearAlgebra

In [2]:
A = Diagonal(3)

MethodError: MethodError: no method matching Diagonal(::Int64)

Closest candidates are:
  Diagonal(!Matched::Diagonal)
   @ LinearAlgebra C:\Users\xingfu_2\AppData\Local\Programs\Julia-1.10.2\share\julia\stdlib\v1.10\LinearAlgebra\src\diagonal.jl:105
  Diagonal(!Matched::Tridiagonal)
   @ LinearAlgebra C:\Users\xingfu_2\AppData\Local\Programs\Julia-1.10.2\share\julia\stdlib\v1.10\LinearAlgebra\src\special.jl:34
  Diagonal(!Matched::Bidiagonal)
   @ LinearAlgebra C:\Users\xingfu_2\AppData\Local\Programs\Julia-1.10.2\share\julia\stdlib\v1.10\LinearAlgebra\src\special.jl:14
  ...


In [3]:
a = Iterators.repeated(-1, 3)

Base.Iterators.Take{Base.Iterators.Repeated{Int64}}(Base.Iterators.Repeated{Int64}(-1), 3)

In [4]:
A = Diagonal(a)

MethodError: MethodError: no method matching Diagonal(::Base.Iterators.Take{Base.Iterators.Repeated{Int64}})

Closest candidates are:
  Diagonal(!Matched::Diagonal)
   @ LinearAlgebra C:\Users\xingfu_2\AppData\Local\Programs\Julia-1.10.2\share\julia\stdlib\v1.10\LinearAlgebra\src\diagonal.jl:105
  Diagonal(!Matched::Tridiagonal)
   @ LinearAlgebra C:\Users\xingfu_2\AppData\Local\Programs\Julia-1.10.2\share\julia\stdlib\v1.10\LinearAlgebra\src\special.jl:34
  Diagonal(!Matched::Bidiagonal)
   @ LinearAlgebra C:\Users\xingfu_2\AppData\Local\Programs\Julia-1.10.2\share\julia\stdlib\v1.10\LinearAlgebra\src\special.jl:14
  ...


In [5]:
b=repeat(-1, 3)

MethodError: MethodError: no method matching repeat(::Int64, ::Int64)

Closest candidates are:
  repeat(!Matched::String, ::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8})
   @ Base strings\substring.jl:260
  repeat(!Matched::Union{SubString{String}, String}, ::Integer)
   @ Base strings\substring.jl:262
  repeat(!Matched::Char, ::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8})
   @ Base strings\string.jl:526
  ...


In [6]:
a=Vector{Float64}(1, 3)

MethodError: MethodError: no method matching Vector{Float64}(::Int64, ::Int64)

Closest candidates are:
  Array{T, N}(!Matched::Missing, ::Any...) where {T, N}
   @ Base baseext.jl:43
  Vector{T}(!Matched::UndefInitializer, ::Int64) where T
   @ Core boot.jl:477
  Array{T, N}(!Matched::UndefInitializer, ::Int64...) where {T, N}
   @ Core boot.jl:483
  ...


In [8]:
v = repeat([5],7)

7-element Vector{Int64}:
 5
 5
 5
 5
 5
 5
 5

In [9]:
v = fill(5, 7)

7-element Vector{Int64}:
 5
 5
 5
 5
 5
 5
 5

In [10]:
v = fill(-1, 3)

3-element Vector{Int64}:
 -1
 -1
 -1

In [11]:
A = Diagonal(v)

3×3 Diagonal{Int64, Vector{Int64}}:
 -1   ⋅   ⋅
  ⋅  -1   ⋅
  ⋅   ⋅  -1

In [12]:
w=ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [13]:
B = Diagonal(w)

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

In [14]:
u=zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [15]:
A2=hcat(A,u)

3×4 Matrix{Float64}:
 -1.0   0.0   0.0  0.0
  0.0  -1.0   0.0  0.0
  0.0   0.0  -1.0  0.0

In [16]:
B2=hcat(u,B)

3×4 Matrix{Float64}:
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [17]:
D=A2+B2

3×4 Matrix{Float64}:
 -1.0   1.0   0.0  0.0
  0.0  -1.0   1.0  0.0
  0.0   0.0  -1.0  1.0

In [18]:
V=D*D'

3×3 Matrix{Float64}:
  2.0  -1.0   0.0
 -1.0   2.0  -1.0
  0.0  -1.0   2.0

In [19]:
cholesky(V)

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.41421  -0.707107   0.0
  ⋅        1.22474   -0.816497
  ⋅         ⋅         1.1547

In [2]:
using LinearAlgebra

In [3]:
n=2
v = fill(-1, n)
A = Diagonal(v)
w=ones(n)
B = Diagonal(w)
u=zeros(n)
A2=hcat(A,u)
B2=hcat(u,B)
D=A2+B2
V=D*D'


2×2 Matrix{Float64}:
  2.0  -1.0
 -1.0   2.0

In [4]:
cholesky(V)

Cholesky{Float64, Matrix{Float64}}
U factor:
2×2 UpperTriangular{Float64, Matrix{Float64}}:
 1.41421  -0.707107
  ⋅        1.22474

In [5]:
V1=inv(V)
cholesky(V1)

Cholesky{Float64, Matrix{Float64}}
U factor:
2×2 UpperTriangular{Float64, Matrix{Float64}}:
 0.816497  0.408248
  ⋅        0.707107

In [22]:
1/6^0.5

0.40824829046386296

In [26]:
3/6^0.5

1.224744871391589

In [6]:
L1 = [2^0.5  -2^0.5/2; 0  3/6^0.5]

2×2 Matrix{Float64}:
 1.41421  -0.707107
 0.0       1.22474

In [7]:
B1= [2/6^0.5  1/6^0.5; 0  2^0.5/2]

2×2 Matrix{Float64}:
 0.816497  0.408248
 0.0       0.707107

In [8]:
L=L1'

2×2 adjoint(::Matrix{Float64}) with eltype Float64:
  1.41421   0.0
 -0.707107  1.22474

In [9]:
V=L*L'

2×2 Matrix{Float64}:
  2.0  -1.0
 -1.0   2.0

In [10]:
B=B1'

2×2 adjoint(::Matrix{Float64}) with eltype Float64:
 0.816497  0.0
 0.408248  0.707107

In [11]:
V1=B*B'

2×2 Matrix{Float64}:
 0.666667  0.333333
 0.333333  0.666667

In [12]:
V*V1

2×2 Matrix{Float64}:
  1.0          -2.22045e-16
 -1.11022e-16   1.0

In [13]:
H20=B*D

2×3 Matrix{Float64}:
 -0.816497   0.816497  0.0
 -0.408248  -0.298858  0.707107

In [14]:
H2=B'*D

2×3 Matrix{Float64}:
 -0.816497   0.408248  0.408248
  0.0       -0.707107  0.707107

In [15]:
h=[2/6^0.5;1/2^0.5]

2-element Vector{Float64}:
 0.8164965809277259
 0.7071067811865475

In [16]:
H=Diagonal(h)

2×2 Diagonal{Float64, Vector{Float64}}:
 0.816497   ⋅ 
  ⋅        0.707107

In [18]:
I = Diagonal(w)
I20=hcat(I,u)
A2=[-0.5   -0.5; 0  -1]
A20=hcat(u,A2)
Ap=I20 + A20

2×3 Matrix{Float64}:
 1.0  -0.5  -0.5
 0.0   1.0  -1.0

In [19]:
A=H*Ap

2×3 Matrix{Float64}:
 0.816497  -0.408248  -0.408248
 0.0        0.707107  -0.707107

In [5]:
ma=[1 2; 3 4]
sp="Hello Geeks"


"Hello Geeks"

In [2]:
tu4 = (1, 2, 3, "Hello Geeks",ma)

(1, 2, 3, "Hello Geeks", [1 2; 3 4])

In [3]:
exs=(1, 2, 3, "Hello Geeks",ma)

(1, 2, 3, "Hello Geeks", [1 2; 3 4])

In [6]:
exs=(sp,ma)

("Hello Geeks", [1 2; 3 4])

In [4]:
blk = Expr(:block)

quote
end

In [7]:
for ex in exs
    push!(blk.args, :(println($(sprint(Base.show_unquoted,ex)*" = "))))
end

In [8]:
blk


quote
    println("\"Hello Geeks\" = ")
    println("[1 2; 3 4] = ")
end

In [9]:
for ex in exs
    push!(blk.args, :(println($(sprint(Base.show_unquoted,ex)*" = "))))
    push!(blk.args, :(show(stdout, "text/plain", begin value=$(esc(ex)) end)))
    push!(blk.args, :(println()))
end

In [10]:
blk

quote
    println("\"Hello Geeks\" = ")
    println("[1 2; 3 4] = ")
    println("\"Hello Geeks\" = ")
    show(stdout, "text/plain", begin
            #= d:\jianguo\myvscode\Julia\test-2024-05-11.ipynb:3 =#
            value = $(Expr(:escape, "Hello Geeks"))
        end)
    println()
    println("[1 2; 3 4] = ")
    show(stdout, "text/plain", begin
            #= d:\jianguo\myvscode\Julia\test-2024-05-11.ipynb:3 =#
            value = $(Expr(:escape, [1 2; 3 4]))
        end)
    println()
end

In [1]:
14*8

112

In [1]:
15*9

135